[context.production.environment]
  REACT_APP_HABAHABA_URL = "https://be.gohaba.com"
  REACT_APP_HABAHABA_SUBSCRIPTION_URL = "wss://gohaba-prod.herokuapp.com"

[context.develop.environment]
  REACT_APP_HABAHABA_URL = "https://haba-be-staging.herokuapp.com"
  REACT_APP_HABAHABA_SUBSCRIPTION_URL = "wss://haba-be-staging.herokuapp.com"
